function(find_apple_framework FRAMEWORK_NAME FRAMEWORK_VAR)
    find_library(${FRAMEWORK_VAR} NAMES ${FRAMEWORK_NAME} PATHS /System/Library/Frameworks NO_DEFAULT_PATH)
    if(NOT ${FRAMEWORK_VAR})
        message(FATAL_ERROR "Could not find ${FRAMEWORK_NAME}")
    endif()
endfunction()

function(create_apple_frameworks_target TARGET_NAME RESULT_VAR)
    set(FRAMEWORKS_FOUND TRUE)
    foreach(FRAMEWORK IN LISTS ARGN)
        find_apple_framework(${FRAMEWORK} FRAMEWORK_PATH)
        if(NOT FRAMEWORK_PATH)
            set(FRAMEWORKS_FOUND FALSE)
            break()
        endif()
        list(APPEND FRAMEWORK_PATHS ${FRAMEWORK_PATH})
    endforeach()

    if(FRAMEWORKS_FOUND)
        add_library(${TARGET_NAME} INTERFACE)
        target_link_libraries(${TARGET_NAME} INTERFACE ${FRAMEWORK_PATHS})
        set(${RESULT_VAR} TRUE PARENT_SCOPE)
    else()
        message(WARNING "One or more Apple frameworks not found")
        set(${RESULT_VAR} FALSE PARENT_SCOPE)
    endif()
endfunction()